#!/usr/bin/env bash

layout=`setxkbmap -query | grep layout`

if [[ "$layout" != *"woynert" ]]; then
	setxkbmap woynert
else
	setxkbmap latam
fi

notify-send "$(setxkbmap -query | grep layout | awk '{print "layout",toupper($2)}')"
