#!/usr/bin/env bash

layout=`setxkbmap -query | grep layout`

if [[ "$layout" != *"us" ]]; then
	setxkbmap us
else
	setxkbmap latam
fi

notify-send "$(setxkbmap -query | grep layout | awk '{print "layout",toupper($2)}')"
