#import = [ "~/.config/alacritty/theme-light.toml" ]
import = [ "~/.config/alacritty/theme-dark.toml" ]

[font]
size = 10.0

[font.bold]
style = "Medium"

[font.normal]
family = "mono"
style = "Medium"

[font.offset]
x = 0
y = -4

[window]
dynamic_padding = true

[window.padding]
x = 4
y = 0
